#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The SubuwuTuner Authors
"""
cousin_seed — clone an existing pack TOML to a sibling CID as an RE seed.

Many Subaru CIDs the community has stock dumps for are not covered by any
public RomRaider XML — typically post-2009 firmware revisions of a family
already represented in `definitions/`. Example: we have an A2TB100K pack
(USDM 2007 Legacy GT MT) and a forum-attached A2TB100Z.bin stock dump,
but no XML for A2TB100Z. A2TB100Z is almost certainly a closely-related
firmware revision; its table addresses are *probably* the same or close.

cousin_seed generates a starting-point TOML by copying the base pack and
swapping CID-bearing fields. The result is an EDUCATED GUESS, not a
verified pack — every address still needs byte-validation against the
target ROM (rom-info, dump-table sanity check, rom_diff_localize against
any tuned variant of the target CID, etc.). The output file carries a
prominent "COUSIN SEED" header to keep that fact visible.

Usage:
    python cousin_seed.py --base definitions/legacy/a2tb100k.toml \
                          --cid A2TB100Z \
                          -o definitions/legacy/a2tb100z.toml

The base pack must be a normal SubuwuTuner pack TOML with a single
`[[identification]]` block (the common case). Multi-identification packs
trigger a warning and pick the first block.

What gets swapped:
- `[pack].id`             → new CID (lowercase)
- `[pack].display_name`   → new CID (uppercase)
- `[[identification]].name` → new CID (uppercase)
- `[[identification]].cid_match` → new CID (uppercase)
- `[[identification]].ecu_part` → cleared (must be set by the validator
                                   from the target ROM's ecuid byte range)
- `[[identification]].cid_address` → dropped, `cid_scan = true` substituted
                                   The base's address was computed against
                                   the base CID's ROM layout (or carried
                                   defgen's old wrong `0x00000000` default).
                                   Either way it does not necessarily match
                                   the NEW CID's offset, so we scan for the
                                   CID string instead. `rom-info` will catch
                                   any case where scan can't find it.
- `[[identification]].cid_length` → dropped (loader infers from
                                   `len(cid_match)` under scan mode)

What stays:
- Every table address, scaling, axis. These are the cousin assumption —
  the WHOLE POINT of seeding from a related pack. The user then runs
  validation tooling to confirm or correct each one.
- platform, transmission, years, rom_size_bytes, endianness, includes,
  checksum_type — these are typically the same across a CID family.

The output file replaces the defgen header comment with a COUSIN-SEED
notice that names the base pack and lists the validation steps still
required.
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path


_HEADER = """\
# COUSIN-SEED pack — generated by tools/defgen/cousin_seed.py.
#
# This pack was created by cloning {base_rel} and swapping the
# CID-bearing fields to {new_cid_upper}. Table addresses, scalings,
# and axes are inherited UNVERIFIED from the base pack on the
# assumption that {new_cid_upper} is a close firmware revision of
# {base_cid_upper}. **THIS IS A SEED, NOT A VERIFIED DEFINITION.**
#
# Validation checklist before relying on this pack:
#   1. `rom-info --def <this> <target.bin>` must report `Match:` with
#      the right CID at a sensible offset.
#   2. `dump-table --def <this> --table <id> <target.bin>` for 3-4
#      representative tables (boost_target, fuel_main, ignition_main,
#      coolant_temp_axis) must produce values in plausible ranges.
#   3. If a tuned variant of the target CID is available,
#      `tools/rom_diff_localize.py` against {{stock,tuned}} of the
#      target should resolve clusters to table-IDs in this pack. Any
#      cluster pointing at an unlabeled byte range means the address
#      shifted between {base_cid_upper} and {new_cid_upper}; patch
#      the offending table.
#   4. `ecu_part` was cleared — set it from the target ROM's ecuid
#      byte range (typically `0x{ecu_part_hint}` for this family,
#      verify with the live ROM).
#
# Once validated end-to-end, replace this header with the standard
# defgen header and the COUSIN-SEED filename suffix (if any).

"""


def _read_pack_text(path: Path) -> str:
    return path.read_text(encoding="utf-8")


def _strip_defgen_header(text: str) -> str:
    """Drop the leading `# Generated by tools/defgen ...` block.

    The header is a contiguous run of `#`-prefixed lines plus surrounding
    blank lines, ending before the first `[pack]` (or other non-comment)
    content. We delete everything up to (but not including) the first
    line that begins with `[` or a non-`#` non-empty token.
    """
    lines = text.splitlines(keepends=True)
    cutoff = 0
    for i, line in enumerate(lines):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            cutoff = i + 1
            continue
        break
    return "".join(lines[cutoff:])


def _section_slice(text: str, section: str) -> tuple[int, int] | None:
    """Find the byte range of one TOML section in `text`.

    `section` is the literal header line, e.g. `[pack]` or
    `[[identification]]`. Returns (start, end) where `start` is the
    char index of the first line after the header and `end` is the
    char index of the next `[`-prefixed header (or len(text) if none).
    Returns None if the header isn't found.

    Bounded by section headers rather than blank lines so that an
    inner-block field (like `[[identification]].name`) won't be
    confused with the same field name in a later block (like
    `[[table]].name`).
    """
    header_pat = rf'^{re.escape(section)}\s*$'
    m = re.search(header_pat, text, flags=re.MULTILINE)
    if not m:
        return None
    start = m.end()
    next_section = re.search(r'^\[', text[start:], flags=re.MULTILINE)
    end = start + next_section.start() if next_section else len(text)
    return start, end


def _swap_field(text: str, key: str, new_value: str, *,
                section: str | None = None) -> tuple[str, bool]:
    """Replace the first `key = "<anything>"` line. Returns (text, ok).

    When `section` is given, the swap is restricted to within that
    TOML section's slice — necessary to disambiguate keys that recur
    across sections (e.g. `id` appears in [pack], every [[scaling]],
    and every [[table]]; without scoping the first hit could land
    anywhere).
    """
    pattern = rf'^(\s*{re.escape(key)}\s*=\s*)"[^"]*"'
    replacement = rf'\1"{new_value}"'

    if section is None:
        new_text, n = re.subn(pattern, replacement, text, count=1,
                              flags=re.MULTILINE)
        return new_text, (n == 1)

    slc = _section_slice(text, section)
    if slc is None:
        return text, False
    start, end = slc
    before, body, after = text[:start], text[start:end], text[end:]
    new_body, n = re.subn(pattern, replacement, body, count=1,
                          flags=re.MULTILINE)
    return (before + new_body + after), (n == 1)


def _clear_field(text: str, key: str, *,
                 section: str | None = None) -> tuple[str, bool]:
    """Set `key = ""`. Same anchoring rules as _swap_field."""
    return _swap_field(text, key, "", section=section)


def _force_cid_scan(text: str, *, section: str) -> tuple[str, bool]:
    """Switch the named section to `cid_scan = true`, dropping any
    `cid_address` / `cid_length` lines.

    Cousin-seeded packs cannot trust the base's `cid_address` — the offset
    where the CID string lands in flash is firmware-revision-specific, and
    the base's value (or defgen's old `0x00000000` default) is meaningless
    for the new CID. Scan mode delegates the lookup to the loader, which
    walks the ROM for `cid_match`.

    Idempotent: if `cid_scan = true` already exists in the section, no-op.
    Returns (new_text, changed).
    """
    slc = _section_slice(text, section)
    if slc is None:
        return text, False
    start, end = slc
    before, body, after = text[:start], text[start:end], text[end:]

    if re.search(r'^\s*cid_scan\s*=\s*true\s*$', body, re.MULTILINE):
        return text, False

    # Replace cid_address line with cid_scan line; if no cid_address
    # was present, insert cid_scan above cid_match. Pad the field name
    # to match defgen's 12-char alignment.
    new_body, addr_n = re.subn(
        r'^(\s*)cid_address\s*=\s*0x[0-9A-Fa-f]+\s*\n',
        r"\1cid_scan     = true\n",
        body,
        count=1,
        flags=re.MULTILINE,
    )
    if addr_n == 0:
        new_body = re.sub(
            r'^(\s*)cid_match\s*=',
            r"\1cid_scan     = true\n\1cid_match   =",
            body,
            count=1,
            flags=re.MULTILINE,
        )

    # Drop cid_length entirely (loader derives it from len(cid_match)).
    new_body = re.sub(
        r'^\s*cid_length\s*=\s*\d+\s*\n',
        "",
        new_body,
        count=1,
        flags=re.MULTILINE,
    )
    return (before + new_body + after), True


def seed_pack(base_text: str,
              new_cid: str,
              *,
              base_rel: str,
              base_cid: str | None = None) -> str:
    """Pure function: take base pack text + new CID, return seed text.

    Exposed for testing without filesystem I/O.
    """
    new_cid_upper = new_cid.upper()
    new_cid_lower = new_cid.lower()

    body = _strip_defgen_header(base_text)

    # Try to recover the base CID from the existing [[identification]]
    # block if the caller didn't supply one (rare path).
    if base_cid is None:
        m = re.search(r'^\s*cid_match\s*=\s*"([^"]+)"', body, re.MULTILINE)
        base_cid = m.group(1) if m else "UNKNOWN"
    base_cid_upper = base_cid.upper()

    # Pull the existing ecu_part to populate the validation hint, then
    # clear the field in the body.
    ecu_part_hint = ""
    m = re.search(r'^\s*ecu_part\s*=\s*"([^"]+)"', body, re.MULTILINE)
    if m:
        ecu_part_hint = m.group(1)

    # Swap CID-bearing fields, each restricted to its own TOML
    # section so that `id` in [[scaling]] / [[table]] blocks isn't
    # touched. Every swap must succeed or we abort — silently missing
    # any one would produce a seed with a mixed-CID identity.
    swaps = [
        ("[pack]",             "id",           new_cid_lower),
        ("[pack]",             "display_name", new_cid_upper),
        ("[[identification]]", "name",         new_cid_upper),
        ("[[identification]]", "cid_match",    new_cid_upper),
    ]
    for section, key, value in swaps:
        body, ok = _swap_field(body, key, value, section=section)
        if not ok:
            raise ValueError(
                f"base pack missing required field: {key} (in {section})"
            )

    # ecu_part absence is fine — the validator will populate it from
    # the target ROM's ecuid bytes anyway.
    body, _ = _clear_field(body, "ecu_part", section="[[identification]]")

    # Force scan mode: the base's cid_address was computed for the BASE
    # CID's offset (or carried defgen's old wrong 0x00000000 default).
    # Either way it does not necessarily match the NEW CID's location.
    body, _ = _force_cid_scan(body, section="[[identification]]")

    # Strip the base's per-CID ecuparams from the includes list — those
    # encode SSM extended-PID addresses specific to the base CID, and
    # would feed wrong bytes to a datalogger targeting the new CID.
    # The shared `../pids.toml` (protocol-level addresses, universal
    # across all SSM-capable ECUs) is safe to keep.
    body = re.sub(
        r'^(includes\s*=\s*)\[[^\]]*\]',
        lambda m: m.group(1) + '["../pids.toml"]',
        body,
        count=1,
        flags=re.MULTILINE,
    )

    header = _HEADER.format(
        base_rel=base_rel,
        new_cid_upper=new_cid_upper,
        base_cid_upper=base_cid_upper,
        ecu_part_hint=ecu_part_hint or "?",
    )
    return header + body


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(
        prog="cousin_seed",
        description="Seed a SubuwuTuner pack TOML by cloning a sibling CID.",
    )
    ap.add_argument("--base", required=True, type=Path,
                    help="Path to the base pack TOML to clone from.")
    ap.add_argument("--cid", required=True,
                    help="The new CID to seed (e.g. A2TB100Z). "
                         "Case-folded as needed.")
    ap.add_argument("-o", "--output", type=Path,
                    help="Output path. Default: stdout.")
    args = ap.parse_args(argv)

    if not args.base.is_file():
        print(f"cousin_seed: base pack not found: {args.base}",
              file=sys.stderr)
        return 2

    text = _read_pack_text(args.base)
    try:
        # Show the base path relative to the repo root if we can guess
        # it; falls back to the absolute path.
        base_rel = args.base.as_posix()
        cwd = Path.cwd().as_posix().rstrip("/") + "/"
        if base_rel.startswith(cwd):
            base_rel = base_rel[len(cwd):]
        seeded = seed_pack(text, args.cid, base_rel=base_rel)
    except ValueError as e:
        print(f"cousin_seed: {e}", file=sys.stderr)
        return 1

    if args.output:
        args.output.write_text(seeded, encoding="utf-8")
        print(f"wrote {args.output}", file=sys.stderr)
    else:
        sys.stdout.write(seeded)
    return 0


if __name__ == "__main__":
    sys.exit(main())
