"""
shopping_list.py
================

Produce a clean "what to buy from ecutune" report from the existing
cluster_survey.py logic, but emit ALL cluster members (not truncated
to 8) so the user can pick whichever ECU ID ecutune actually carries.

Output: roms_extracted/ecutune_shopping_list.txt
"""

from __future__ import annotations

import sys
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))
from cluster_survey import (  # type: ignore
    ENC, BLUDGOD, FORUM_BINS, JIMIHIMI,
    HEADER_BY_SIZE, cluster_bucket,
)

OUT = HERE / "roms_extracted" / "ecutune_shopping_list.txt"


def collect_plaintexts() -> set[str]:
    have: set[str] = set()
    for root in (BLUDGOD, FORUM_BINS, JIMIHIMI):
        if not root.exists():
            continue
        for p in root.rglob("*"):
            if p.is_file() and p.suffix.lower() in (".bin", ".hex", ".rom"):
                eid = p.stem.upper().split("-")[0].split("_")[0][:8]
                have.add(eid)
    return have


def main() -> int:
    have_plain = collect_plaintexts()

    by_size: dict[int, list[Path]] = defaultdict(list)
    for p in ENC.glob("*_ori.hex"):
        by_size[p.stat().st_size].append(p)

    lines: list[str] = []
    push = lines.append

    push("=" * 78)
    push("ecutune shopping list  (auto-generated by shopping_list.py)")
    push("=" * 78)
    push(f"plaintexts on hand : {len(have_plain)}")
    push(f"cipher buckets     : {len(by_size)}")
    push(f"total cipher files : {sum(len(v) for v in by_size.values())}")
    push("")
    push("How to read:")
    push("  Each LOCKED cluster = N cipher files sharing one keystream.")
    push("  Buying ANY one ECU ID from the member list (as a plaintext .bin)")
    push("  recovers that keystream and decrypts all N ciphers in the cluster.")
    push("  Pick whichever ID ecutune actually sells; they all unlock the same set.")
    push("")

    # Aggregate locked clusters across all buckets for the ranked summary.
    all_locked: list[tuple[int, int, list[str], str]] = []  # (size, count, members, bucket_label)

    for size in sorted(by_size):
        files = sorted(by_size[size])
        hdr = HEADER_BY_SIZE.get(size, 1024)
        push("-" * 78)
        push(f"BUCKET  size={size:,} bytes   header={hdr}   files={len(files)}")
        push("-" * 78)

        clusters = cluster_bucket(files, hdr)
        bucket_label = f"{size:,}B"

        # Sort: largest first, locked before broken
        ordered = sorted(
            clusters.values(),
            key=lambda m: (any(e in have_plain for e in m), -len(m)),
        )
        for members in ordered:
            broken = any(eid in have_plain for eid in members)
            tag = "[BROKEN]" if broken else "[LOCKED]"
            push(f"  {tag} cluster size={len(members)}  anchor={members[0]}")
            # 6 IDs per line for readability
            for i in range(0, len(members), 6):
                push("        " + "  ".join(f"{m:<10}" for m in members[i:i + 6]))
            if not broken:
                all_locked.append((size, len(members), members, bucket_label))
            push("")
        push("")

    push("=" * 78)
    push("RANKED SHOPPING LIST  (highest-leverage LOCKED clusters first)")
    push("=" * 78)
    push("")
    all_locked.sort(key=lambda t: -t[1])
    cumulative = 0
    for rank, (size, count, members, label) in enumerate(all_locked, 1):
        cumulative += count
        push(f"#{rank}  unlocks {count:>3} ciphers  (bucket {label})  cumulative={cumulative}")
        push(f"     buy any ONE of:")
        for i in range(0, len(members), 6):
            push("       " + "  ".join(f"{m:<10}" for m in members[i:i + 6]))
        push("")

    push("=" * 78)
    push(f"Buying top 5 anchors unlocks "
         f"{sum(c for _, c, _, _ in all_locked[:5])} ciphers.")
    push(f"Buying top 10 anchors unlocks "
         f"{sum(c for _, c, _, _ in all_locked[:10])} ciphers.")
    push(f"Buying ALL  {len(all_locked)} anchors unlocks "
         f"{sum(c for _, c, _, _ in all_locked)} ciphers.")
    push("=" * 78)

    OUT.write_text("\n".join(lines), encoding="utf-8")
    print(f"wrote {OUT}  ({len(lines)} lines)")
    # Echo the ranked summary block to stdout
    for line in lines[lines.index("RANKED SHOPPING LIST  (highest-leverage LOCKED clusters first)") - 1:]:
        print(line)
    return 0


if __name__ == "__main__":
    sys.exit(main())
