# SPDX-License-Identifier: Apache-2.0
# Copyright 2026 The SubuwuTuner Authors
"""Unit tests for cousin_seed.py."""

from __future__ import annotations

import sys
import textwrap
import unittest
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import cousin_seed  # noqa: E402


_BASE_PACK = textwrap.dedent("""\
    # Generated by tools/defgen from a public RomRaider EcuFlash-format XML
    # source. Only factual ECU data is reproduced; descriptive text is stripped
    # per the clean-room rules in docs/01-reverse-engineering.md. Hand-edit any
    # descriptions you want in this file; defgen will not overwrite them unless
    # you re-run it explicitly.


    [pack]
    schema_version = 1
    id             = "a2tb100k"
    display_name   = "A2TB100K"
    platform       = "subaru.legacy"
    transmission   = "mt"
    years          = [7]
    endianness     = "big"
    rom_size_bytes = 1048576
    license        = "Apache-2.0"
    includes       = ["../ecuparams/a2tb100k.toml", "../pids.toml"]


    [[identification]]
    name        = "A2TB100K"
    cid_address = 0x00002000
    cid_length  = 8
    cid_match   = "A2TB100K"
    ecu_part    = "5204784007"


    [[scaling]]
    id        = "boost_target_bar"
    formula   = "linear"
    factor    = 1.0
    offset    = 0.0
""")


class CousinSeedSwapTest(unittest.TestCase):
    def test_swaps_cid_bearing_fields(self):
        seeded = cousin_seed.seed_pack(_BASE_PACK, "A2TB100Z",
                                       base_rel="definitions/legacy/a2tb100k.toml")
        # pack id is lowercased
        self.assertIn('id             = "a2tb100z"', seeded)
        # display_name is uppercase
        self.assertIn('display_name   = "A2TB100Z"', seeded)
        # identification name + cid_match both uppercase
        self.assertIn('name        = "A2TB100Z"', seeded)
        self.assertIn('cid_match   = "A2TB100Z"', seeded)

    def test_clears_ecu_part(self):
        seeded = cousin_seed.seed_pack(_BASE_PACK, "A2TB100Z",
                                       base_rel="definitions/legacy/a2tb100k.toml")
        # ecu_part must be empty in the [[identification]] block — the
        # validator fills it in from the target ROM's ecuid bytes. The
        # old value still appears in the header's "hint" line, which is
        # the intended cue for the validator.
        body = seeded.split("[pack]", 1)[1]
        self.assertIn('ecu_part    = ""', body)
        self.assertNotIn('5204784007', body)

    def test_preserves_tables_and_scalings(self):
        seeded = cousin_seed.seed_pack(_BASE_PACK, "A2TB100Z",
                                       base_rel="definitions/legacy/a2tb100k.toml")
        # The boost_target_bar scaling block is preserved verbatim.
        self.assertIn('id        = "boost_target_bar"', seeded)
        self.assertIn('factor    = 1.0', seeded)

    def test_preserves_pack_metadata(self):
        seeded = cousin_seed.seed_pack(_BASE_PACK, "A2TB100Z",
                                       base_rel="definitions/legacy/a2tb100k.toml")
        # Platform, transmission, years, rom_size_bytes, license: all
        # carry through (these are CID-family-stable).
        self.assertIn('platform       = "subaru.legacy"', seeded)
        self.assertIn('rom_size_bytes = 1048576', seeded)
        self.assertIn('transmission   = "mt"', seeded)

    def test_strips_base_per_cid_ecuparams_from_includes(self):
        # Base includes `../ecuparams/a2tb100k.toml` — those SSM
        # extended-PID addresses are CID-specific and would be wrong
        # for the seed's target CID. Seed retains only `../pids.toml`.
        seeded = cousin_seed.seed_pack(_BASE_PACK, "A2TB100Z",
                                       base_rel="definitions/legacy/a2tb100k.toml")
        self.assertIn('includes       = ["../pids.toml"]', seeded)
        self.assertNotIn('a2tb100k.toml', seeded.split("[pack]", 1)[1])

    def test_emits_cousin_seed_header(self):
        seeded = cousin_seed.seed_pack(_BASE_PACK, "A2TB100Z",
                                       base_rel="definitions/legacy/a2tb100k.toml")
        # Header must lead with the COUSIN-SEED marker and name the base.
        self.assertTrue(seeded.startswith("# COUSIN-SEED pack"))
        self.assertIn("definitions/legacy/a2tb100k.toml", seeded)
        self.assertIn("A2TB100Z", seeded)
        self.assertIn("A2TB100K", seeded)
        # The validation checklist must be present.
        self.assertIn("Validation checklist", seeded)
        self.assertIn("rom-info", seeded)

    def test_strips_defgen_header(self):
        seeded = cousin_seed.seed_pack(_BASE_PACK, "A2TB100Z",
                                       base_rel="definitions/legacy/a2tb100k.toml")
        # The "Generated by tools/defgen from a public RomRaider" line is
        # part of the defgen header and must NOT survive — the seed has
        # its own header.
        self.assertNotIn("Generated by tools/defgen", seeded)

    def test_case_folding_on_cid_argument(self):
        # User passes lowercase; we still emit the canonical forms.
        seeded = cousin_seed.seed_pack(_BASE_PACK, "a2tb100z",
                                       base_rel="definitions/legacy/a2tb100k.toml")
        self.assertIn('id             = "a2tb100z"', seeded)
        self.assertIn('cid_match   = "A2TB100Z"', seeded)

    def test_ecu_part_hint_lands_in_header(self):
        seeded = cousin_seed.seed_pack(_BASE_PACK, "A2TB100Z",
                                       base_rel="definitions/legacy/a2tb100k.toml")
        # The header mentions the base pack's old ecu_part as a starting
        # hint for the validator.
        self.assertIn("5204784007", seeded)

    def test_scaling_id_not_touched(self):
        # Regression: the previous unscoped _swap_field would land
        # `id = "..."` on the first match anywhere in the file. With
        # section scoping, only [pack].id is swapped — [[scaling]].id
        # stays exactly as authored.
        seeded = cousin_seed.seed_pack(
            _BASE_PACK, "A2TB100Z",
            base_rel="definitions/legacy/a2tb100k.toml")
        scaling_section = seeded.split("[[scaling]]", 1)[1]
        self.assertIn('id        = "boost_target_bar"', scaling_section)
        self.assertNotIn('id        = "a2tb100z"', scaling_section)

    def test_forces_scan_mode_dropping_base_cid_address(self):
        # The base pack carries cid_address = 0x00002000 + cid_length = 8
        # for A2TB100K. The seeded pack for A2TB100Z must NOT carry that
        # address — A2TB100Z's CID string lives at a different (unknown)
        # offset. Cousin-seed must emit cid_scan = true and drop both
        # cid_address and cid_length so the loader scans the target ROM.
        seeded = cousin_seed.seed_pack(
            _BASE_PACK, "A2TB100Z",
            base_rel="definitions/legacy/a2tb100k.toml")
        ident = seeded.split("[[identification]]", 1)[1].split("[[", 1)[0]
        self.assertIn("cid_scan     = true", ident)
        self.assertNotIn("cid_address", ident)
        self.assertNotIn("cid_length", ident)

    def test_scan_mode_idempotent_when_base_already_scans(self):
        # If the base pack is already in cid_scan = true mode, the seed
        # should still come out in scan mode (and not add a duplicate
        # cid_scan line).
        scan_base = _BASE_PACK.replace(
            "cid_address = 0x00002000\n    cid_length  = 8\n",
            "cid_scan    = true\n",
        )
        seeded = cousin_seed.seed_pack(
            scan_base, "A2TB100Z",
            base_rel="definitions/legacy/a2tb100k.toml")
        ident = seeded.split("[[identification]]", 1)[1].split("[[", 1)[0]
        self.assertEqual(ident.count("cid_scan"), 1)
        self.assertIn("true", ident)

    def test_missing_required_field_raises(self):
        # Each of the four CID-bearing field swaps must abort if the
        # base pack lacks the source line — silently skipping any one
        # of them would produce a seed with mixed-CID identity.
        line_to_remove = {
            "id":           'id             = "a2tb100k"',
            "display_name": 'display_name   = "A2TB100K"',
            "name":         'name        = "A2TB100K"',
            "cid_match":    'cid_match   = "A2TB100K"',
        }
        for field, line in line_to_remove.items():
            with self.subTest(field=field):
                bad = _BASE_PACK.replace(line, '')
                with self.assertRaises(ValueError) as cm:
                    cousin_seed.seed_pack(
                        bad, "A2TB100Z",
                        base_rel="definitions/legacy/a2tb100k.toml")
                self.assertIn(field, str(cm.exception))


if __name__ == "__main__":
    unittest.main()
