// SPDX-License-Identifier: Apache-2.0
// Copyright 2026 The SubuwuTuner Authors
//
// FileInfo2 codec + cmd 0x20 / 0x21 / 0x22 / 0x25 / 0x26 request
// pinning tests. The canonical fixtures live at fixtures/ap3/ and
// were generated by the analyst-side toolkit from Frida-captured
// wire bytes — see fixtures/ap3/REQUEST_FIXTURES_README.md.
//
// The legacy `fileinfo2_known_good.bin` was synthesized from spec §7
// and is documented WRONG (see the 2026-06-11 PM handoff). It still
// exists on disk for archaeology but is no longer the source of
// truth; this file does not pin against it.

#include "st/devices/ap3/client.hpp"
#include "st/devices/ap3/file_info.hpp"
#include "st/transport/cobb_ap_packet.hpp"

#include <catch2/catch_test_macros.hpp>

#include <array>
#include <cstdint>
#include <filesystem>
#include <fstream>
#include <ios>
#include <span>
#include <string>
#include <vector>

namespace {

std::vector<std::uint8_t> load_fixture(char const *name) {
    std::filesystem::path p = std::filesystem::path{ST_FIXTURE_AP3_DIR} / name;
    std::ifstream in{p, std::ios::binary | std::ios::ate};
    if (!in) {
        return {};
    }
    auto const sz = in.tellg();
    in.seekg(0);
    std::vector<std::uint8_t> bytes(static_cast<std::size_t>(sz));
    in.read(reinterpret_cast<char *>(bytes.data()), sz);
    return bytes;
}

void require_bytes_equal(std::vector<std::uint8_t> const &got,
                         std::vector<std::uint8_t> const &expected) {
    REQUIRE(got.size() == expected.size());
    for (std::size_t i = 0; i < expected.size(); ++i) {
        INFO("byte " << i << " got=" << std::hex << static_cast<int>(got[i])
                     << " expected=" << static_cast<int>(expected[i]));
        REQUIRE(got[i] == expected[i]);
    }
}

} // namespace

TEST_CASE("ap3 FileInfo: uleb128 round-trip helper still works",
          "[devices][ap3]") {
    // uleb128 is no longer the FileInfo2 string-length encoding (the
    // wire uses u32 LE — see file_info.hpp for the §7 correction).
    // The helper is retained for any future Boost-archive carrier
    // that does use uleb128; this test pins it as a standalone codec.
    for (std::uint64_t v : {std::uint64_t{0}, std::uint64_t{1}, std::uint64_t{127},
                            std::uint64_t{128}, std::uint64_t{72173}, std::uint64_t{1 << 20}}) {
        auto bytes = st::devices::ap3::detail::encode_uleb128(v);
        auto back = st::devices::ap3::detail::read_uleb128(bytes);
        REQUIRE(back.has_value());
        REQUIRE(back->value == v);
        REQUIRE(back->bytes_consumed == bytes.size());
    }
}

TEST_CASE("ap3 FileInfo: encode_file_info opens with the 35-byte request envelope",
          "[devices][ap3]") {
    st::devices::ap3::FileInfo info{};
    info.name = "Stage0.ptm";
    info.path = "maps/Stage0.ptm";
    info.mtime = 0;
    info.size = 50000;

    auto encoded = st::devices::ap3::encode_file_info(info);
    REQUIRE(encoded.has_value());
    REQUIRE(encoded->size() >= st::devices::ap3::kBoostEnvelope.size());
    for (std::size_t i = 0; i < st::devices::ap3::kBoostEnvelope.size(); ++i) {
        REQUIRE((*encoded)[i] == st::devices::ap3::kBoostEnvelope[i]);
    }
    // Class registration follows the envelope.
    REQUIRE((*encoded)[st::devices::ap3::kBoostEnvelope.size()] == 0x00);
    REQUIRE((*encoded)[st::devices::ap3::kBoostEnvelope.size() + 1] == 0x01);
}

TEST_CASE("ap3 FileInfo: encode uses u32 LE string lengths, NOT uleb128",
          "[devices][ap3]") {
    // The §7 daze trigger was uleb128-instead-of-u32-LE; the
    // request-fixture handoff (2026-06-11) inverted the spec text.
    // For name "abc" (3 bytes) the wire shape after the 37-byte
    // header (35-envelope + 2-class-reg) is `03 00 00 00 'a' 'b' 'c'`.
    st::devices::ap3::FileInfo info{};
    info.name = "abc";
    info.path = "x";
    auto encoded = st::devices::ap3::encode_file_info(info);
    REQUIRE(encoded.has_value());
    constexpr std::size_t kNameLenOffset =
        st::devices::ap3::kBoostEnvelope.size() + 2; // + class reg
    REQUIRE(encoded->size() > kNameLenOffset + 7);
    REQUIRE((*encoded)[kNameLenOffset] == 0x03);
    REQUIRE((*encoded)[kNameLenOffset + 1] == 0x00);
    REQUIRE((*encoded)[kNameLenOffset + 2] == 0x00);
    REQUIRE((*encoded)[kNameLenOffset + 3] == 0x00);
    REQUIRE((*encoded)[kNameLenOffset + 4] == 'a');
    REQUIRE((*encoded)[kNameLenOffset + 5] == 'b');
    REQUIRE((*encoded)[kNameLenOffset + 6] == 'c');
}

TEST_CASE("ap3 FileInfo: field order is name → metadata → path",
          "[devices][ap3]") {
    // Verify the 27-byte metadata block sits BETWEEN the name and the
    // path, not after both. This was the other spec §7 misread —
    // emitting in name/path/metadata order dazes the AP firmware.
    st::devices::ap3::FileInfo info{};
    info.name = "n";
    info.path = "p";
    auto encoded = st::devices::ap3::encode_file_info(info);
    REQUIRE(encoded.has_value());
    constexpr std::size_t kHeader = st::devices::ap3::kBoostEnvelope.size() + 2;
    // Offset of name byte: header + 4 (u32 LE name_len) = 41
    // Offset of metadata start: 41 + 1 (name) = 42
    // Offset of path len:       42 + 27 = 69
    // Offset of path byte:      69 + 4 = 73
    REQUIRE((*encoded)[kHeader + 4] == 'n');
    // 27 zero metadata bytes follow.
    for (std::size_t i = 0; i < 27; ++i) {
        REQUIRE((*encoded)[kHeader + 5 + i] == 0x00);
    }
    // u32 LE path_len = 1.
    REQUIRE((*encoded)[kHeader + 5 + 27] == 0x01);
    REQUIRE((*encoded)[kHeader + 5 + 27 + 1] == 0x00);
    REQUIRE((*encoded)[kHeader + 5 + 27 + 4] == 'p');
}

TEST_CASE("ap3 FileInfo: encode/decode round-trip preserves name+path+mtime+size",
          "[devices][ap3]") {
    st::devices::ap3::FileInfo info{};
    info.name = "Fehr_DMann CAN 93 ETune (Reflash-WRK3).ptm";
    info.path = "maps/Fehr_DMann CAN 93 ETune (Reflash-WRK3).ptm";
    info.mtime = 1717612345;
    info.size = 72245;

    auto encoded = st::devices::ap3::encode_file_info(info);
    REQUIRE(encoded.has_value());
    auto decoded = st::devices::ap3::decode_file_info(*encoded);
    REQUIRE(decoded.has_value());
    REQUIRE(decoded->name == info.name);
    REQUIRE(decoded->path == info.path);
    REQUIRE(decoded->mtime == info.mtime);
    REQUIRE(decoded->size == info.size);
}

TEST_CASE("ap3 FileInfo: encode rejects mtime + size that overflow u32",
          "[devices][ap3]") {
    // The AP firmware reads the metadata as u32 LE mtime + u32 LE
    // size + 19 opaque bytes (not u64 + u64 + 11 as spec §7
    // originally claimed). Any caller-provided value > u32 would
    // truncate silently; require an explicit error instead.
    st::devices::ap3::FileInfo info{};
    info.name = "x";
    info.path = "x";
    info.mtime = 0x1'0000'0000ULL;
    auto encoded = st::devices::ap3::encode_file_info(info);
    REQUIRE_FALSE(encoded.has_value());

    info.mtime = 0;
    info.size = 0x1'0000'0000ULL;
    auto encoded2 = st::devices::ap3::encode_file_info(info);
    REQUIRE_FALSE(encoded2.has_value());
}

TEST_CASE("ap3 FileInfo: decode rejects a truncated archive prefix",
          "[devices][ap3]") {
    std::array<std::uint8_t, 10> tiny{0x16, 0x00, 0x00, 0x00, 0x73, 0x65,
                                      0x72, 0x69, 0x61, 0x6C};
    auto decoded = st::devices::ap3::decode_file_info(tiny);
    REQUIRE_FALSE(decoded.has_value());
}

// ---------------------------------------------------------------------------
// String-body carrier (cmd 0x21, cmd 0x26)
// ---------------------------------------------------------------------------

TEST_CASE("ap3 FileInfo: encode_string_body opens with the 35-byte envelope",
          "[devices][ap3]") {
    auto encoded = st::devices::ap3::encode_string_body("maps");
    REQUIRE(encoded.has_value());
    REQUIRE(encoded->size() == st::devices::ap3::kBoostEnvelope.size() + 4 + 4);
    for (std::size_t i = 0; i < st::devices::ap3::kBoostEnvelope.size(); ++i) {
        REQUIRE((*encoded)[i] == st::devices::ap3::kBoostEnvelope[i]);
    }
    // u32 LE length = 4 immediately after envelope.
    REQUIRE((*encoded)[st::devices::ap3::kBoostEnvelope.size()] == 0x04);
    REQUIRE((*encoded)[st::devices::ap3::kBoostEnvelope.size() + 1] == 0x00);
    REQUIRE((*encoded)[st::devices::ap3::kBoostEnvelope.size() + 2] == 0x00);
    REQUIRE((*encoded)[st::devices::ap3::kBoostEnvelope.size() + 3] == 0x00);
    // Then the string bytes.
    REQUIRE((*encoded)[st::devices::ap3::kBoostEnvelope.size() + 4] == 'm');
    REQUIRE((*encoded)[st::devices::ap3::kBoostEnvelope.size() + 7] == 's');
}

// ---------------------------------------------------------------------------
// Fixture-driven pins — the load-bearing checks. The new request
// fixtures are the source of truth for the wire format; encoder
// drift surfaces here.
// ---------------------------------------------------------------------------

namespace {

// Encode the full packet (sync magic → CRC trailer) for cmd `type`
// with a FileInfo2 body and pin it against the named fixture.
void pin_fileinfo2_packet(char const *fixture_name, std::uint8_t cmd,
                          st::devices::ap3::FileInfo const &info) {
    auto fixture = load_fixture(fixture_name);
    if (fixture.empty()) {
        SKIP("fixture not staged");
    }
    auto body = st::devices::ap3::encode_file_info(info);
    REQUIRE(body.has_value());
    auto packet = st::transport::ap3::encode_packet(cmd, *body);
    REQUIRE(packet.has_value());
    require_bytes_equal(*packet, fixture);
}

void pin_string_packet(char const *fixture_name, std::uint8_t cmd,
                       std::string_view s) {
    auto fixture = load_fixture(fixture_name);
    if (fixture.empty()) {
        SKIP("fixture not staged");
    }
    auto body = st::devices::ap3::encode_string_body(s);
    REQUIRE(body.has_value());
    auto packet = st::transport::ap3::encode_packet(cmd, *body);
    REQUIRE(packet.has_value());
    require_bytes_equal(*packet, fixture);
}

} // namespace

TEST_CASE("ap3 request: cmd 0x20 backupcksum pins byte-for-byte (CRC = 0x547a5f4a)",
          "[devices][ap3][fixtures]") {
    // Load-bearing cross-check per REQUEST_FIXTURES_README.md: this
    // fixture's CRC matches a Frida-captured live APManager packet.
    // If our encoder produces these bytes, every other request shape
    // is verified by transitivity.
    st::devices::ap3::FileInfo info{};
    info.name = "backupcksum";
    info.path = "backupcksum";
    info.mtime = 0;
    info.size = 0;
    pin_fileinfo2_packet("cmd20_backupcksum_request_known_good.bin", 0x20U, info);

    // Independently verify the CRC value the analyst called out.
    auto fixture = load_fixture("cmd20_backupcksum_request_known_good.bin");
    REQUIRE(fixture.size() == 105);
    std::uint32_t const crc =
        (static_cast<std::uint32_t>(fixture[101]) << 24) |
        (static_cast<std::uint32_t>(fixture[102]) << 16) |
        (static_cast<std::uint32_t>(fixture[103]) << 8) |
        static_cast<std::uint32_t>(fixture[104]);
    REQUIRE(crc == 0x547a5f4aU);
}

TEST_CASE("ap3 request: cmd 0x20 ReadFile setup (test.ptm @ /maps/) pins byte-for-byte",
          "[devices][ap3][fixtures]") {
    st::devices::ap3::FileInfo info{};
    info.name = "test.ptm";
    info.path = "/maps/";
    info.mtime = 0;
    info.size = 0;
    pin_fileinfo2_packet("cmd20_readfile_setup_request_known_good.bin", 0x20U, info);
}

TEST_CASE("ap3 request: cmd 0x22 PutFile setup (mtime populated) pins byte-for-byte",
          "[devices][ap3][fixtures]") {
    st::devices::ap3::FileInfo info{};
    info.name = "test.ptm";
    info.path = "maps/test.ptm";
    info.mtime = 0x12345678U;
    info.size = 0;
    pin_fileinfo2_packet("cmd22_putfile_setup_request_known_good.bin", 0x22U, info);
}

TEST_CASE("ap3 request: cmd 0x25 RemoveFile pins byte-for-byte",
          "[devices][ap3][fixtures]") {
    st::devices::ap3::FileInfo info{};
    info.name = "test.ptm";
    info.path = "maps/test.ptm";
    info.mtime = 0;
    info.size = 0;
    pin_fileinfo2_packet("cmd25_removefile_request_known_good.bin", 0x25U, info);
}

TEST_CASE("ap3 request: cmd 0x21 GetFile step 2 (session-id string) pins byte-for-byte",
          "[devices][ap3][fixtures]") {
    pin_string_packet("cmd21_getfile_request_known_good.bin", 0x21U, "C:/tmp/test.ptm");
}

TEST_CASE("ap3 request: cmd 0x26 ListFiles (dir=\"maps\") pins byte-for-byte",
          "[devices][ap3][fixtures]") {
    pin_string_packet("cmd26_listfiles_request_known_good.bin", 0x26U, "maps");
}

// ---------------------------------------------------------------------------
// Response decoders — these still target the older 30-byte-prefix
// response shapes. Real captured responses for cmd 0x20 / 0x22 setup
// ACKs are not yet staged; the list-response decoder pin below
// exercises the only response shape we have on disk.
// ---------------------------------------------------------------------------

TEST_CASE("ap3 fixtures: boost_archive_header.bin matches kBoostArchivePrefix exactly",
          "[devices][ap3][fixtures]") {
    auto bytes = load_fixture("boost_archive_header.bin");
    if (bytes.empty()) {
        SKIP("fixture not available");
    }
    REQUIRE(bytes.size() == st::devices::ap3::kBoostArchivePrefix.size());
    for (std::size_t i = 0; i < bytes.size(); ++i) {
        REQUIRE(bytes[i] == st::devices::ap3::kBoostArchivePrefix[i]);
    }
}

TEST_CASE("ap3 FileInfo: decode_file_info_list parses canonical /presets/ capture",
          "[devices][ap3][fixtures]") {
    // Real cmd 0x26 response packet captured from a married AP for
    // /presets/. 319 bytes total / 3 records. The 319 bytes are a
    // full wire packet: 7-byte header + body + 4-byte CRC. Strip
    // both to get the body the decoder expects.
    auto bytes = load_fixture("fileinfo2_list_response_known_good.bin");
    if (bytes.empty()) {
        SKIP("vector<FileInfo2> response fixture not staged");
    }
    REQUIRE(bytes.size() == 319);
    REQUIRE(bytes.size() >= 11U);
    std::span<std::uint8_t const> body{bytes.data() + 7U, bytes.size() - 7U - 4U};
    REQUIRE(body.size() == 308);

    auto records = st::devices::ap3::decode_file_info_list(body);
    REQUIRE(records.has_value());
    REQUIRE(records->size() == 3);

    REQUIRE((*records)[0].name == "VA WRX Dmann Logger.cfg");
    REQUIRE((*records)[1].name == "CANGatewayTroubleshoot.cfg");
    REQUIRE((*records)[2].name == "CANGatewayGeneral.cfg");
    for (auto const &r : *records) {
        REQUIRE(r.path.find("presets/") != std::string::npos);
    }
}

TEST_CASE("ap3 FileInfo: decode_file_info_list rejects implausible record count",
          "[devices][ap3]") {
    std::vector<std::uint8_t> body;
    body.insert(body.end(), st::devices::ap3::kFileInfo2Prefix.begin(),
                st::devices::ap3::kFileInfo2Prefix.end());
    body.push_back(0x08U);
    body.push_back(0x01U);
    body.push_back(0x00U);
    body.push_back(0x00U);
    body.push_back(0xFFU);
    body.push_back(0xFFU);
    body.push_back(0xFFU);
    body.push_back(0xFFU);
    body.push_back(0x00U);
    body.push_back(0x00U);
    body.push_back(0x00U);
    body.push_back(0x00U);
    body.push_back(0x01U);
    auto records = st::devices::ap3::decode_file_info_list(body);
    REQUIRE_FALSE(records.has_value());
    REQUIRE(records.error().code() == st::ErrorCode::ParseError);
}

TEST_CASE("ap3 split_ap_path: basic forms", "[devices][ap3]") {
    auto a = st::devices::ap3::split_ap_path("/maps/Stage0.ptm");
    REQUIRE(a.name == "Stage0.ptm");
    REQUIRE(a.path == "/maps/");

    auto b = st::devices::ap3::split_ap_path("/backupcksum");
    REQUIRE(b.name == "backupcksum");
    REQUIRE(b.path == "/");

    auto c = st::devices::ap3::split_ap_path("bare");
    REQUIRE(c.name == "bare");
    REQUIRE(c.path == "/");
}

TEST_CASE("decode_setup_ack_response_shape: backupcksum-style happy path",
          "[devices][ap3][file_info]") {
    // Build a synthetic setup ACK body matching the live /backupcksum
    // capture: 30-byte prefix + 7-byte fixed block + name_len + name +
    // mtime + size + 19 flags + path_len + path.
    std::vector<std::uint8_t> body;
    body.insert(body.end(), st::devices::ap3::kFileInfo2Prefix.begin(),
                st::devices::ap3::kFileInfo2Prefix.end());
    // 7-byte fixed block 08 01 00 00 00 00 01
    body.insert(body.end(), {0x08, 0x01, 0x00, 0x00, 0x00, 0x00, 0x01});
    // u32 LE name_len = 11
    body.insert(body.end(), {0x0b, 0x00, 0x00, 0x00});
    // name = "backupcksum"
    std::string const name = "backupcksum";
    body.insert(body.end(), name.begin(), name.end());
    // mtime = 454 (0x000001c6 LE)
    body.insert(body.end(), {0xc6, 0x01, 0x00, 0x00});
    // size = 33 (0x00000021 LE)
    body.insert(body.end(), {0x21, 0x00, 0x00, 0x00});
    // 19-byte flags (zero)
    body.insert(body.end(), 19, std::uint8_t{0});
    // u32 LE path_len = 11
    body.insert(body.end(), {0x0b, 0x00, 0x00, 0x00});
    // path = "backupcksum"
    body.insert(body.end(), name.begin(), name.end());

    auto result = st::devices::ap3::decode_setup_ack_response_shape(body);
    REQUIRE(result.has_value());
    REQUIRE(result->name == "backupcksum");
    REQUIRE(result->mtime == 454U);
    REQUIRE(result->size == 33U);
    REQUIRE(result->path == "backupcksum");
}

TEST_CASE("decode_setup_ack_response_shape: degenerate ACK (name='.', size=0)",
          "[devices][ap3][file_info]") {
    // The AP firmware's path-resolution bug for subdirectory files
    // (live-confirmed 2026-06-12) returns name="." and size=0 — this
    // shape must decode successfully so the caller can detect it and
    // fail fast instead of waiting for a cmd 0x21 timeout.
    std::vector<std::uint8_t> body;
    body.insert(body.end(), st::devices::ap3::kFileInfo2Prefix.begin(),
                st::devices::ap3::kFileInfo2Prefix.end());
    body.insert(body.end(), {0x08, 0x01, 0x00, 0x00, 0x00, 0x00, 0x01});
    body.insert(body.end(), {0x01, 0x00, 0x00, 0x00}); // name_len = 1
    body.push_back(0x2e);                              // name = "."
    body.insert(body.end(), {0x00, 0x00, 0x00, 0x00}); // mtime = 0
    body.insert(body.end(), {0x00, 0x00, 0x00, 0x00}); // size = 0
    body.insert(body.end(), 19, std::uint8_t{0});      // 19 flags
    body.insert(body.end(), {0x06, 0x00, 0x00, 0x00}); // path_len = 6
    std::string const path = "/maps/";
    body.insert(body.end(), path.begin(), path.end());

    auto result = st::devices::ap3::decode_setup_ack_response_shape(body);
    REQUIRE(result.has_value());
    REQUIRE(result->name == ".");
    REQUIRE(result->size == 0U);
    REQUIRE(result->path == "/maps/");
}

TEST_CASE("decode_setup_ack_response_shape: truncated body rejects",
          "[devices][ap3][file_info]") {
    // Too short for even the prefix + fixed block.
    std::vector<std::uint8_t> tiny(10, std::uint8_t{0});
    auto result = st::devices::ap3::decode_setup_ack_response_shape(tiny);
    REQUIRE_FALSE(result.has_value());
}

TEST_CASE("decode_setup_ack_response_shape: prefix-magic mismatch rejects",
          "[devices][ap3][file_info]") {
    std::vector<std::uint8_t> body(100, std::uint8_t{0xff}); // wrong magic
    auto result = st::devices::ap3::decode_setup_ack_response_shape(body);
    REQUIRE_FALSE(result.has_value());
}
