#!/usr/bin/env python3
"""Compare RH850/LHB definition tables with analyst calibration indexes.

This is an offline evidence report. An exact address match means that a
definition table starts at an address present in the corresponding analyst
index; it does not authorize a write, prove table semantics, or open an RH850
flash/codegen region.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
import tomllib
from pathlib import Path
from typing import Any


KEY_TABLES = (
    "engine_displacement",
    "fuel_timing_hpfp_base_offset",
    "fuel_timing_hpfp_phase_transfer_curve",
    "fuel_pulse_direct_injector_flow",
    "fuel_injectors_pulse_injector_mult_table",
    "avcs_intake_base_target_normal_tgvs_closed_baro_low",
    "avcs_intake_base_target_normal_tgvs_closed_baro_high",
)


def parse_hex(value: Any) -> int | None:
    if isinstance(value, int):
        return value
    if isinstance(value, str):
        try:
            return int(value, 0)
        except ValueError:
            return None
    return None


def load_index(path: Path) -> tuple[list[dict[str, str]], set[int]]:
    lines = path.read_text(encoding="utf-8").splitlines()
    if not lines:
        return [], set()
    header = lines[0].lstrip("#").strip().split("\t")
    rows = list(csv.DictReader(lines[1:], fieldnames=header, delimiter="\t"))
    addresses: set[int] = set()
    for row in rows:
        address = parse_hex(row.get("address"))
        if address is not None:
            addresses.add(address)
    return rows, addresses


def normalize_table(table: dict[str, Any]) -> dict[str, Any]:
    return {
        "id": str(table.get("id", "")),
        "address": parse_hex(table.get("address")),
        "dimensions": table.get("dimensions"),
        "data_type": table.get("data_type", ""),
    }


def build_result(definition: Path, decompile_root: Path) -> dict[str, Any]:
    pack = tomllib.loads(definition.read_text(encoding="utf-8"))
    tables = [normalize_table(t) for t in pack.get("table", [])]
    tables_with_address = [t for t in tables if t["address"] is not None]
    definition_addresses = {t["address"] for t in tables_with_address}

    cid = definition.stem.lower()
    index_path = decompile_root / cid / "calibration_index.tsv"
    rows: list[dict[str, str]] = []
    evidence_addresses: set[int] = set()
    if index_path.exists():
        rows, evidence_addresses = load_index(index_path)

    matched = [t for t in tables_with_address if t["address"] in evidence_addresses]
    key_tables: list[dict[str, Any]] = []
    by_id = {t["id"]: t for t in tables}
    for table_id in KEY_TABLES:
        table = by_id.get(table_id)
        key_tables.append(
            {
                "id": table_id,
                "present": table is not None,
                "address": table["address"] if table else None,
                "indexed": bool(table and table["address"] in evidence_addresses),
            }
        )

    category_patterns = {
        "hpfp": re.compile(r"hpfp", re.IGNORECASE),
        "fuel_pressure": re.compile(r"fuel_pressure", re.IGNORECASE),
        "avcs_intake": re.compile(r"avcs_intake", re.IGNORECASE),
        "injector": re.compile(r"injector", re.IGNORECASE),
    }
    categories = {}
    for category, pattern in category_patterns.items():
        subset = [t for t in tables_with_address if pattern.search(t["id"])]
        categories[category] = {
            "definition_tables": len(subset),
            "indexed_tables": sum(t["address"] in evidence_addresses for t in subset),
        }

    return {
        "cid": cid,
        "definition": str(definition),
        "index": str(index_path) if index_path.exists() else None,
        "definition_tables": len(tables),
        "definition_tables_with_address": len(tables_with_address),
        "definition_unique_addresses": len(definition_addresses),
        "evidence_rows": len(rows),
        "evidence_unique_addresses": len(evidence_addresses),
        "indexed_definition_tables": len(matched),
        "indexed_definition_unique_addresses": len(
            {t["address"] for t in matched}
        ),
        "categories": categories,
        "key_tables": key_tables,
    }


def render_markdown(results: list[dict[str, Any]], definitions_root: Path) -> str:
    with_index = [r for r in results if r["index"]]
    indexed = sum(r["indexed_definition_unique_addresses"] for r in with_index)
    evidence = sum(r["evidence_unique_addresses"] for r in with_index)
    lines = [
        "# RH850 definition evidence report",
        "",
        "Generated by `tools/rh850_definition_evidence.py`.",
        "",
        "> This is an offline analyst-evidence report. An exact address match is",
        "> not a write authorization, semantic proof, checksum proof, or RH850",
        "> flash/recovery validation.",
        "",
        f"- Definition root: `{definitions_root}`",
        f"- LHB definitions scanned: **{len(results)}**",
        f"- Matching calibration indexes: **{len(with_index)}**",
        f"- Definition-only packs: **{len(results) - len(with_index)}**",
        f"- Unique indexed definition addresses: **{indexed}**",
        f"- Unique analyst-index addresses: **{evidence}**",
        "",
        "## Per-CID coverage",
        "",
        "| CID | Definition tables | Unique definition addresses | Index rows | Indexed definition addresses | Status |",
        "|---|---:|---:|---:|---:|---|",
    ]
    for result in results:
        status = "indexed" if result["index"] else "definition-only"
        lines.append(
            "| `{cid}` | {definition_tables} | {definition_unique_addresses} | "
            "{evidence_rows} | {indexed_definition_unique_addresses} | {status} |".format(
                **result, status=status
            )
        )

    lines.extend(
        [
            "",
            "## Native FA24 candidate tables",
            "",
            "These IDs are surfaced for tuning-software review. `indexed` means",
            "the table's definition address appears in that CID's analyst index;",
            "`definition-only` means no exact address match was present in the",
            "current index and needs analyst review.",
            "",
            "| CID | Table | Address | Indexed |",
            "|---|---|---:|---|",
        ]
    )
    for result in results:
        for table in result["key_tables"]:
            if not table["present"]:
                continue
            address = (
                f"`0x{table['address']:X}`" if table["address"] is not None else "—"
            )
            lines.append(
                f"| `{result['cid']}` | `{table['id']}` | {address} | "
                f"{'yes' if table['indexed'] else 'no'} |"
            )

    lines.extend(
        [
            "",
            "## Interpretation",
            "",
            "The report is intended to feed definition QA, table-browser evidence",
            "badges, and CID comparison work. It must not be used as a writable",
            "region manifest. RH850 `[[writable_region]]` entries remain gated on",
            "bench validation of FCU programming, bank selection, reset/vector",
            "behavior, checksums, and secondary-bank recovery.",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> int:
    code_root = Path(__file__).resolve().parents[1]
    workspace_root = code_root.parent
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--definitions",
        type=Path,
        default=code_root / "definitions" / "impreza",
        help="directory containing lhb*.toml definitions",
    )
    parser.add_argument(
        "--decompile-root",
        type=Path,
        default=workspace_root / "findings" / "decompile",
        help="directory containing <cid>/calibration_index.tsv",
    )
    parser.add_argument("--out", type=Path, help="write Markdown report")
    parser.add_argument("--json-out", type=Path, help="write JSON report")
    args = parser.parse_args()

    definitions = sorted(args.definitions.glob("lhb*.toml"))
    if not definitions:
        print(f"no LHB definitions found under {args.definitions}", file=sys.stderr)
        return 2

    results = [build_result(path, args.decompile_root) for path in definitions]
    markdown = render_markdown(results, args.definitions)
    document = {
        "tool": "rh850_definition_evidence",
        "definitions_root": str(args.definitions),
        "decompile_root": str(args.decompile_root),
        "results": results,
    }

    if args.out:
        args.out.parent.mkdir(parents=True, exist_ok=True)
        args.out.write_text(markdown, encoding="utf-8")
    else:
        print(markdown, end="")
    if args.json_out:
        args.json_out.parent.mkdir(parents=True, exist_ok=True)
        args.json_out.write_text(json.dumps(document, indent=2) + "\n", encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
